POST http://localhost:8000/signup
Content-Type: application/json

{
    "name":"dhanush",
    "username":"123456dhanush",
    "password":"12345",
    "age" : 23,
    " medicines":{
      "medicine_name":"rantak"
    }
    
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "username":"1234dhanush",
    "password":"12345"
}

###
POST http://localhost:8000/BMI
Content-Type: application/json


{
  "userId": "5fb68295202ebb5b5ac01b5c",
  "age":31,
  "weight":31,
  "height":31
}